spring:
  cloud:
    stream:
#      kafka:
#        binder:
#          brokers:
#          - localhost:9092, localhost:9093, localhost:9094
      bindings:
        position-in-0:
          destination: positions
  kafka:
    producer:
      acks: all
    consumer:
      auto-offset-reset: earliest
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094